# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 前端花园
email: gemeiwangji789@qq.com
description: 在前端的道路上风景更加绚丽多姿
baseurl: "https://beth-zhang.github.io/Frontend-Garden" # the subpath of your site, e.g. /blog
url: "https://github.com/BETH-zhang" # the base hostname & protocol for your site
twitter_username: 
github_username:  BETH-zhang
avatar: 'https://avatars3.githubusercontent.com/u/19342035?v=3&s=40'

# Build settings
markdown: kramdown
